### ISSUE TITLE
8장 영화앱 react-native-make의 splash 질문드립니다.

### ISSUE THREAD

**Issue by morankim** [bjpublic/Reactnative#147]
안녕하세요 저자님. 책 보면서 따라하는 중에 스플래시 스크린을 만들기 위해서 react-native-make를 설치하였습니다. 
그리고 set-icon은 작동했는데 set-splash는 계속 에러가 뜨고 구글링도 되지 않아 혹시 도움을 받을 수 있을까 질문 남겨봅니다!

C:\Users\user\StudioProjects\MovieApp>react-native set-splash --path ./src/Assets/Images/splash.jpg
TypeError: Cannot read properties of null (reading '1')
    at getPackageFileName (C:\Users\user\StudioProjects\MovieApp\node_modules\@bam.tech\react-native-make\dist\utils.js:19:66)
    at Object.getAndroidPackageName (C:\Users\user\StudioProjects\MovieApp\node_modules\@bam.tech\react-native-make\dist\utils.js:34:12)
    at addReactNativeSplashScreen (C:\Users\user\StudioProjects\MovieApp\node_modules\@bam.tech\react-native-make\dist\modules\setSplashScreen\android\service.js:36:115)
    at exports.addAndroidSplashScreen (C:\Users\user\StudioProjects\MovieApp\node_modules\@bam.tech\react-native-make\dist\modules\setSplashScreen\android\service.js:13:9)
    at exports.setSplashScreenTask (C:\Users\user\StudioProjects\MovieApp\node_modules\@bam.tech\react-native-make\dist\modules\setSplashScreen\setSplashScreen.task.js:17:29)
    at async Command.handleAction (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:108:9)

![image](https://user-images.githubusercontent.com/15083315/215725042-be0d5792-b68b-467d-a09c-65d79661ff2b.png)

**Comment by dev-yakuza** [comment]
@morankim 

안녕하세요.

현재 에러 메시지만으로는 큰 도움을 드릴 수 없을거 같습니다만, 혹시 `./src/Assets/Images/splash.jpg`에 이미지 파일이 존재하시는지요?

**Comment by morankim** [comment]
네 미리 3000x3000 크기의 jpg이미지를 폴더안에 저장했는데도 그러네요... 저한테만 생기는 오류 같으니 우선은 splashscreen을 대신하도록 코드를 작성하고 돌려봐야겠네요. 감사합니다.

**Comment by dev-yakuza** [comment]
@morankim 

제가 얼마전에 최신 소스로 업데이트 한 `PR`이 있습니다.

- https://github.com/bjpublic/Reactnative/pull/125

이 코드를 받아서 한번 확인해 보시는 것도 좋을거 같습니다.

그리고 책에서 소개한 `react-native-make`가 `archived`되었습니다.

- https://github.com/bamlab/react-native-make

그래서 공부하실 때만 사용하시고 실전에서는 실제로 이미지를 만들어서 올리시는 것을 권해드립니다.

**Comment by morankim** [comment]
네 말씀해주신대로 참고해서 프로젝트 다시 생성해보겠습니다.  감사합니다!!
